mod TEST-CONSTANTS is
  pr APP-ID .
  pr TA-INSTANCE-ID .
  pr TA-OBJECT-ID .
  pr FILE-ID .
  pr CONFIGURATION .

  op testRa : -> Oid [ctor] .
  op osId : -> Oid .

  op testTa : -> TaInstId [ctor] .

  ops persistentObjId dataStreamId : -> TaObjectId .

  op testFileId : -> FileId .
  op newTestFileId : -> FileId .

  op TESTTA : -> AppId [ctor] .
  
endm

mod TEST-PROGRAM-DECL is
  pr IMP-PROGRAM .

  op sess : -> Var [ctor] .
  op ret : -> Var [ctor] .

  op res : -> Var [ctor] .
  op srcKey : -> Var [ctor] .
  op destKey : -> Var [ctor] .
  op attr : -> Var [ctor] .
  op objDataFlag : -> Var [ctor] .
  op object : -> Var [ctor] .
  op data : -> Var [ctor] .
  op objectInfo : -> Var [ctor] .

  op main : -> FuncId [ctor] .
endm

mod TEST-AUX is
  pr TEST-CONSTANTS .
  pr TEST-PROGRAM-DECL .
endm