mod ENUMERATOR-TEST-CASES is
  pr TEE-BEHAVIOR .
  pr TEE-IMP-BEHAVIOR .
  pr TEST-AUX .

  op testEnumerator : -> Program [ctor] .

  op allocatedEnumeratorExists : -> Stmt [ctor] .
  eq allocatedEnumeratorExists = 
    AllocatePersistentObjectEnumerator(nil ; res, objEnumerator) .

  eq testEnumerator = 
    main () 
    {
      var res ; var objEnumerator ;

      --- For TEE_AllocatePersistentObjectEnumerator
      --- Test Case 1
      --- AllocatePersistentObjectEnumerator(nil ; res, objEnumerator) ;
      --- return res

      --- For TEE_FreePersistentObjectEnumerator
      --- Test Case 1
      --- allocatedEnumeratorExists ;
      --- FreePersistentObjectEnumerator(objEnumerator ;) ;
      --- return res

      --- For TEE_StartPersistentObjectEnumerator
      --- Test Case 1
      --- allocatedEnumeratorExists ;
      --- StartPersistentObjectEnumerator(objEnumerator, # TEE-STORAGE-PRIVATE ; res) ;
      --- return res

      --- For TEE_ResetPersistentObjectEnumerator
      --- Test Case 1
      allocatedEnumeratorExists ;
      StartPersistentObjectEnumerator(objEnumerator, # TEE-STORAGE-PRIVATE ; res) ;
      ResetPersistentObjectEnumerator(objEnumerator ;) ;
      return res
    }
  .
endm