mod GENERIC-TEST-CASES is
  pr TEE-BEHAVIOR .
  pr TEE-IMP-BEHAVIOR .
  pr TEST-AUX .
  pr TRANSIENT-TEST-CASES .
  pr DATA-STREAM-TEST-CASES .

  op testGeneric : -> Program [ctor] .

  eq testGeneric = 
    struct {
        var objectType ;
        var objectSize ;
        var maxObjectSize ; 
        var objectUsage ;
        var dataSize ; 
        var dataPosition ; 
        var handleFlags 
    } TeeObjectInfo ;

    main () 
    {
      var res ; 
      var destKey ;
      var objDataFlag ; var object ;

      --- For TEE_CloseObject
      --- Test Case 1 (Close transient obj's handle)
      --- allocatedTransientObjExists ;
      --- CloseObject(destKey ; destKey) ;
      --- return res

      --- Test Case 2 (Close persistent obj's handle) (Requires scenario with key)
      --- openedHandleToPersistentObj ;
      --- CloseObject(object ; object) ;
      --- return res

      --- For TEE_GetObjectInfo1
      --- Test Case 1
      openedHandleToPersistentObj ;
      struct TeeObjectInfo objectInfo ;
      GetObjectInfo1(object  ; res, objectInfo) ;
      return objectInfo . dataSize

      --- For TEE_GetBufferAttribute
      --- Test Case 1
      --- populatedTransientObjExists ;
      --- GetBufferAttribute(srcKey, # TEE-ATTR-SECRET-VALUE ; res, attr) ;
      --- return attr
    }
  .
endm