mod TEST-CONSTANTS is
  pr APP-ID .
  pr TA-INSTANCE-ID .
  pr CONFIGURATION .

  op testRa : -> Oid [ctor] .
  op testTa : -> TaInstId [ctor] .

  op TESTTA : -> AppId [ctor] .
endm

mod TEST-PROGRAM-DECL is
  pr IMP-PROGRAM .

  op sess : -> Var [ctor] .
  op ret : -> Var [ctor] .

  op res : -> Var [ctor] .
  op srcKey : -> Var [ctor] .
  op destKey : -> Var [ctor] .
  op attr : -> Var [ctor] .

  op main : -> FuncId [ctor] .
endm

mod TEST-AUX is
  pr TEST-CONSTANTS .
  pr TEST-PROGRAM-DECL .
endm