load ../src/main
load ./cases/aux
load ./cases/transient
load ./cases/persistent
load ./cases/data-stream
load ./cases/generic

mod TEST-DRIVER is
  pr TEE-BEHAVIOR .
  pr TEE-IMP-BEHAVIOR .
  pr TEST-AUX .

  var P : Program .

  op initTrustedOSwithNoKey : -> Configuration .
  eq initTrustedOSwithNoKey
  = < osId : TeeOSKernel | opened-session : (sessionId(0) |-> testTa) , session-counter : 1 ,
                           storage : empty , storage-status : (TESTTA |-> storageNormal) ,
                           service-request-ta : noAppId , service-request-ta-inst : noInstId ,
                           service-in : nil , service-out : nil ,
                           temporary-objects : empty > .

  op initTrustedOS : -> Configuration .
  eq initTrustedOS
  = < osId : TeeOSKernel | opened-session : (sessionId(0) |-> testTa) , session-counter : 1 ,
                           storage : TESTTA |-> testFileId , storage-status : (TESTTA |-> storageNormal) ,
                           service-request-ta : noAppId , service-request-ta-inst : noInstId ,
                           service-in : nil , service-out : nil ,
                           temporary-objects : empty > .

  
  op testKey : -> Configuration .
  eq testKey = 
    < persistentObjId : PersistentObject | handle-set : none , object-type : TEE-TYPE-DATA , max-object-size : 0 Bits  , 
                                           file-id : testFileId , trust-app-id : TESTTA ,
                                           attribute-set : empty , object-usage-set : empty , data-stream-id : dataStreamId >
    < dataStreamId : DataStreamObject | data-size : dataSize(1) , content : newContent(attrContentData(randomAttrVal)) >
  .

  --- op initRa : Program -> Configuration .
  --- eq initRa(P) = < ra : RichApp | proc : none , prog : P , running : false , 
  ---                                 invoke-req-queue : nil , invoke-ret-queue : nil > .

  op initTestTa : Program -> Configuration .
  eq initTestTa(P) = < testTa : TrustApp | proc : none , prog : P , running : false ,
                                           app-status : normal , api-call : noCall , api-return : noReturn ,
                                           current-api : noApi , api-state : noState , current-params : empty , id-counter : 0 ,
                                           trust-app-id : TESTTA ,
                                           task : task({sessionId(0) , main , nil} , testRa) , task-counter : 0, state-changed : false > .

endm

mod TEST-CASES is
  pr TRANSIENT-TEST-CASES .
  pr PERSISTENT-TEST-CASES .
  pr DATA-STREAM-TEST-CASES .
  pr GENERIC-TEST-CASES .
endm

mod TEST-SCENARIO is
  pr TEST-DRIVER .
  pr TEST-CASES .  

  var P : Program .

  op scenarioWithoutKey : Program -> Configuration .
  eq scenarioWithoutKey(P)
    = initTestTa(P) initTrustedOSwithNoKey .

  op scenarioWithKey : Program -> Configuration .
  eq scenarioWithKey(P)
    = initTestTa(P) initTrustedOS testKey .
endm

--- rew scenarioWithoutKey(testTransient) .
--- rew scenarioWithoutKey(testPersistent) .
--- rew scenarioWithKey(testPersistent) .
--- rew scenarioWithKey(testDataStream) .
--- rew scenarioWithoutKey(testGeneric) .
rew scenarioWithKey(testGeneric) .
