fmod K-COMPUTATION is
  sort K .
  op .K : -> K [ctor] .
  op _~>_ : K K -> K [ctor prec 70 assoc id: .K] .

  sorts KLabel .
  subsorts KLabel < K .
endfm


fmod K-CONFIG is
  inc K-COMPUTATION .
  sorts KConfig .
  op none : -> KConfig [ctor] .
  op __ : KConfig KConfig -> KConfig [ctor assoc comm id: none] .

  sort KConfigItem .
  subsorts KConfigItem < KConfig .
  op k : K -> KConfig [ctor] .
endfm
